FROM --platform=$BUILDPLATFORM nginx:1.25.1
ARG TARGETPLATFORM
ARG BUILDPLATFORM

WORKDIR /etc/nginx

RUN openssl req -nodes -x509 -newkey rsa:2048 -days 365 \
    -subj "/C=CA/ST=BC/L=Victoria/O=UVic/CN=us-west.gcp.clarkzjw.ca" \
    -keyout server-key.pem -out server-cert.pem

COPY etc/nginx/conf.d/livesim2.conf /etc/nginx/conf.d/default.conf
