write_files:
- path: /root/CLOUD_INIT_WAS_HERE

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get update
  - sudo apt-get install wget curl rsync htop build-essential git cmake pkg-config libssl-dev golang screen gnupg2 ca-certificates lsb-release ubuntu-keyring vnstat net-tools -y
  - sudo apt-get install python3 python3-dev python3-pip python3-virtualenv -y
  - sudo apt-get purge -y man-db
  - sudo apt-get upgrade -y
  - sudo systemctl stop snapd
  - sudo apt remove --purge --assume-yes snapd gnome-software-plugin-snap
  - rm -rf /root/snap/
  - sudo rm -rf /var/cache/snapd/ 
  - curl -fsSL https://get.docker.com | bash
  - curl -SL https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
  - echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
  - sudo apt-get update
  - sudo apt-get install nginx -y
