write_files:
- path: /root/CLOUD_INIT_WAS_HERE

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get update
  - sudo apt-get install wget curl rsync htop build-essential git cmake pkg-config libssl-dev golang screen gnupg2 ca-certificates lsb-release ubuntu-keyring vnstat net-tools -y
  - sudo apt-get install python3 python3-dev python3-pip python3-virtualenv -y
  - sudo apt-get purge -y man-db
  - sudo apt-get upgrade -y
  - curl -fsSL https://get.docker.com | bash
