version: '3.1'
services:
  stats:
    image: starlink-dashjs-live-stats-server
    build: ./
    environment:
      LATENCY_TEST_INTERVAL_SECONDS: 1
    ports:
      - 8000:8000

  mongo:
    image: mongo:4.4.22
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: starlink
      MONGO_INITDB_ROOT_PASSWORD: starlink

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: starlink
      ME_CONFIG_MONGODB_ADMINPASSWORD: starlink
      ME_CONFIG_MONGODB_URL: mongodb://starlink:starlink@mongo:27017/

volumes:
  mongodb:
